spring:
  profiles:
    active: local
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  http:
    encoding:
      charset: UTF-8
  data:
    rest:
      base-path: /api
      default-page-size: 10
      max-page-size: 10
  devtools:
    livereload:
      enabled: true
#logging:
 # level:
  #  org:
   #   hibernate:
    #    type: trace





